### ISSUE TITLE
[Feature request / Question] Allow drag'n drop of item name to "Filter bar" and "Search bar"

### ISSUE THREAD

**Issue by garry-ut99** [tablacus/TablacusExplorer#805]
Like the title says, I didn't find so far such a functionality, but I'm not sure if it exists or not, if not, then it's to be considered a feature request: There should be a way to quickly and easily fill "Filter bar" and "Search bar" with a file name or folder name, by the following ways:
- A) after dragging a file or a folder to "Filter bar" or "Search bar" and  releasing
  - currently after doing it, there appears a ![Image](https://github.com/user-attachments/assets/efbaa100-37c1-4772-b8d0-bae322304c08) that it's impossible
  - there exist "Drag and Drop" add-ons from section 6.2 but they don't provide such a functionality
- B) some hot-keys
- C) file / folder context menu options: Send name to "Filter bar" and Send name to "Search bar"
  -  there exists a "Send to" add-on but it doesn't offer such a functionality.

It's faster than manually copying file/folder name and then pasting to Filter/Search bar. It's useful when we want to quickly populate search/filter input field with a base file/folder name (which then can be eventually modified further) to find all files/folder which have same or similar names (especially when having a folder with many files/folders with many groups of similiar filenames). Especially in usage scenarios where we need to repeat such searching many times in a row.

**Comment by ccfs** [comment]
Try this script. You can add it to TE as a hot key or tool bar button with type "JScript".
```
//Filter current file list with names of selected items
const Selected = FV.SelectedItems();
if (Selected && Selected.Count) {
	const aNames = [];
	for (let i = 0; i < Selected.Count; i++) {
		aNames.push("*" + Selected.Item(i).Name + "*");
	}
	SetFilterView(FV, aNames.join(";"));
}
```

**Comment by garry-ut99** [comment]
It works, both as a hot key and as a tollbar button, it also works as a context menu.

But I've noticed an issue with the current script solution: everytime after "Filter bar" is filled with the filename, I sometimes need to modify the text in "Filter bar" before searching, and when I'm trying to do it: when selecting some text in "Filter bar" (to remove it), instead of text selection, the whole filename is being highllighted blue and dragged unnecessarily. 

The workaround/hack is very cumbersome and time consuming,  need to: 
1] _click LMB_ 
2] _wait 1 sec_
3] _then click LMB again_
4] _then wait 1 sec again_ 
5] _then click LMB again_

Then and only then I'm able to select text. The issue doesn't happen when using "Filter bar" in normal conditions, it occurs only with the provided script, so it seems to be a some glitch or an unwanted artifact.

<hr>
 
Also it seems "Drag and Drop" to be a bit more intuitive and easier, so I would like to still have "Drag and Drop" implemented as well.

**Comment by ccfs** [comment]
The [patch](https://github.com/tablacus/TablacusExplorer/issues/692) has been updated to support drag-n-drop to Filter bar to filter and search.

**Comment by garry-ut99** [comment]
OK, it works with Tablacus Explorer and Windows Explorer, so I'm partially/mostly satisfied.

However, I forgot to mention about other tools wherein it might be useful to support drag n drop.
For example it doesn't work with: https://hluk.github.io/CopyQ/
Given a fact that ![Image](https://github.com/user-attachments/assets/efbaa100-37c1-4772-b8d0-bae322304c08) icon doesn't appear, and actually a `+` char appears, like when drag'n'dropping from TE or WE, it seems that maybe it could work with such a MultiClipboard tools? Not sure whether it's matter of TE to implement supporting it or it is some glitch in TE to be fixed. Drag n dropping from CopyQ to applications like Notepad++ works just fine.


![Image](https://github.com/user-attachments/assets/f8a10049-3cb6-4a0b-a14d-3efc99ef4cff)

**Comment by ccfs** [comment]
Other than files/folders, only plain text can be dropped to Filter bar as if it were typed (but not with WebView, I don't know why).
I don't know how to let TE recognise drag-n-drop from CopyQ.

**Comment by garry-ut99** [comment]
> ccfs : but not with WebView, I don't know why

It partially works when using IE11 engine, but still somehow broken: 
- it doesn't autosearch after drag n drop, as it requires additional click to make a search 
(which doesn't happen when drag n drop from TE or WE), means the behavior is inconsistent
- after another drag n drops it inserts text instead of replacing it 
(which doesn't happen doesn't happen when drag n drop from TE or WE) - so again the behavior is inconsistent

![Image](https://github.com/user-attachments/assets/a90b5924-843c-47ab-9665-a4bc4c77197f)

**Comment by ccfs** [comment]
I have updated the patch so that dropping text to the bar will work similarly to dropping files.
It now works with CopyQ v7.1 on Windows 7. I cannot test it with the latest v9.1 which requires Windows 10.

**Comment by garry-ut99** [comment]
> ccfs: It now works with CopyQ v7.1 on Windows 7. 

I agree, it works now fine in Windows 7 SP1 with CopyQ v7.1, on both IE11 and WebView2 engines.

> ccsf: I cannot test it with the latest v9.1 which requires Windows 10.

You can test in virtual machine. It works fine for me in Windows 10 Pro 22H2 VM with the latest CopyQ 9.1.0, on both IE11 and WebView2 engines.

<hr>

But it still doesn't work properly with Ditto (https://ditto-cp.sourceforge.io/). Dropped text turns into "text_5", "text_6", "text_7" and so on, it occurs on both Win 7 & Win 10 and on both IE11 & WV2.

![Image](https://github.com/user-attachments/assets/4ddc581b-2de1-48ec-95aa-3393b3868ec3)

**Comment by ccfs** [comment]
I think that the problem is in Ditto. "text_n" is the name of the file storing the copied data. Ditto should return the copied data, not the file name.

**Comment by garry-ut99** [comment]
I don't deny that it might turn out to be a Ditto's issue, but are you sure, because it doesn't happen when drag n dropping into:
- Firefox search bar (CTRL + F)
- Chromium search bar (CTRL + F)
- Youtube search bar

On the other hand I noticed something in Notepad++ when drag n dropping from Ditto into Notepad++'s tab bar - "text_n" is being put as a name of a new tab, but still the word is pasted correctly in the editor itself.
![Image](https://github.com/user-attachments/assets/2889766f-5b2d-4c51-96ee-ef3c59fcce63)

**Comment by ccfs** [comment]
I just found a solution: change Ditto advanced option "Add file drop when dragging clips" to False.
![Image](https://github.com/user-attachments/assets/80380764-db24-401a-bf54-9c4f5964b7b8)

**Comment by garry-ut99** [comment]
Like I already mentioned in my previous comment:

> gary-ut99: it occurs on Win 7 (Ditto 3.22.2.0.0) & Win 10 (Ditto 3.33.0)

On Win 7 SP1 the latest working version of Ditto for me was 3.22.2.0.0 which lacks "Add file drop when dragging clips" feature.

I couldn't run any newer versions of Ditto than 3.22.2.0.0 on Win 7 SP1: the GUI didn't show up, only the ditto.exe process was running in background in the Task Manager, but Ditto didn't work, nor Ditto showed up on the screen, when pressing hotkeys.

But now I have solved this problem, and was able to run newest version of Ditto on Win 7 SP1, so yes, it works fine with "Add file drop when dragging clips" set to False. 

It works fine also on Win 10 22H2 Virtual Machine.

Hence I'm going to close the thread as the feature has been implemented and all related issues fixed (and I'm satisfied).


<hr>

As for the unability to run Ditto versions newer than 3.22.2.0.0 on Win 7 Sp1 for me, it was caused by this ugly memory leak bug, wherein NET 6 based app eat additional 4GB of RAM:
- https://github.com/dotnet/runtime/issues/79469

NET devs refused to fix this ugly bug as NET Famework 6.0 is not officialy supported on Win 7 SP1 anymore. And if an user tries to fix this memory bug on his own, by toggling some NET runtime flags, then some NET-based aps like the newest Bulk Crap Uninstaller and Ditto might stop running. Toggling back the flags, makes the aps run again, but at the same time the memory leak bug is back. So I use currently a bat script, which temporary enable flags, then run the app, then disable the flags. This script successfully runs the newest versions of Bulk Crap Uninstaller and Ditto, while keeping the ugly NET memory leak bug fixed system wide. If the newest versions of Ditto or Bulk Crap Uninstaller run fine for you without such a bat script, then this means you never toggled these flags, and you suffer the ugly 4 GB RAM NET memory leak, and most likely you are unaware of it as it eats 4 GB of ram in the background, without being visible in process.exe RAM usage in Task Manager because it's the NET library which eats it, not the process.exe itself, and you can see the 4 GB RAM eaten in the commit stack.

**Comment by ccfs** [comment]
I used Ditto portable version 3.24.246. I did not get any problem. This may be because my .NET Framework is the old version 3.5.1 which comes with Win 7.

**Comment by garry-ut99** [comment]
Most likely. I wonder how you can live with so old version of NET like 3.5.1, given many important applications require newer versions, this is what I have:

![Image](https://github.com/user-attachments/assets/73f790cc-a15a-4a23-a6d9-009ac33e74c5)

**Comment by ccfs** [comment]
Your initial request was "to find all files/folder which have same or **_similar names_**". Therefore it is possible to show false hits.

**Comment by garry-ut99** [comment]
Ok, you're right, I confused the both issues.
